#kubectl apply -k dir/.
#kubectl apply -k argo-rollout-canary/argo-cd/.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo-rollouts
resources:
  - resources/namespace.yml
  - https://github.com/argoproj/argo-rollouts/releases/latest/download/install.yaml
  - resources/argo-cd.yml