apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: myapp2
  name: myapp
spec:
  project: default
  source:
    repoURL: https://github.com/saitejdandge/servicemesh.git
    targetRevision: HEAD
    path: single-versioned-deployment/app
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp2
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
