apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: myapp3
  name: myapp3
spec:
  project: default
  source:
    repoURL: https://github.com/saitejdandge/servicemesh.git
    targetRevision: HEAD
    path: argo-rollout-canary/app
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp3
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true