apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: login-rollout
  labels:
    app: login
spec:
  replicas: 10
  selector:
    matchLabels:
      app: login
      version: v1
  template:
    spec:
      containers:
        - image: user-image:v2
          name: login-beta
          imagePullPolicy: Never
    metadata:
      labels:
        app: login
        version: v1
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: { }
        - setWeight: 80
        - pause: { duration: 1m }
        - setWeight: 100
      trafficRouting:
        istio:
          virtualService:
            name: login-virtual-service
            routes:
              - primary
          destinationRule:
            name: login
            canarySubsetName: v2
            stableSubsetName: v1