apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: login-rollout
  labels:
    app: login
    version: v1
spec:
  replicas: 4
  selector:
    matchLabels:
      app: login
      version: v1
  template:
    spec:
      containers:
        - image: user-image:v1
          name: login
          imagePullPolicy: Never
    metadata:
      labels:
        app: login
        version: v1
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {}
        - setWeight: 80
        - pause: {30}
        - setWeight: 100
      trafficRouting:
        istio:
          virtualService:
            name: login-virtual-service
          destinationRule:
            name: login
            canarySubsetName: v2
            stableSubsetName: v1