apiVersion: v1
kind: Service
metadata:
  name: stable-svc
  labels:
    app: stable-svc
spec:
  selector:
    app: myapp3
  ports:
    - port: 4000
      targetPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: canary-svc
  labels:
    app: canary-svc
spec:
  selector:
    app: myapp3
  ports:
    - port: 4000
      targetPort: 3000
