apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: virtual-svc
  labels:
    app: virtual-svc
spec:
  hosts:
    - "*"
  gateways:
    - gateway
  http:
    - match:
        - uri:
            exact: /
      route:
        - destination:
            host: stable-svc
            port:
              number: 4000
          weight: 60
        - destination:
            host: canary-svc
            port:
              number: 4000
          weight: 40
