apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: login-virtual-service
spec:
  hosts:
    - login
  http:
    - route:
        - destination:
            host: login
            subset: v1
          weight: 50
        - destination:
            host: login
            subset: v2
          weight: 50