apiVersion: v1
kind: Service
metadata:
  name: login
  labels:
    app: login
    service: login
spec:
  ports:
    - port: 3000
      name: http
  selector:
    app: login

---
#Deployment v1

#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: login-v1
#  labels:
#    app: login
#    version: v1
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: login
#      version: v1
#  template:
#    spec:
#      containers:
#        - image: v1-new-app:0.0.1
#          name: nginx
#          imagePullPolicy: Never
#    metadata:
#      labels:
#        app: login
#        version: v1

---

#Deployment2
apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-v2
  labels:
    app: login
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login
      version: v2
  template:
    spec:
      containers:
        - image: v1-new-app:0.0.1
          name: nginx
          imagePullPolicy: Never
    metadata:
      labels:
        app: login
        version: v2


---
#Dashboard
apiVersion: v1
kind: Service
metadata:
  name: dashboard
  labels:
    app: dashboard
    service: dashboard
spec:
  ports:
    - port: 4000
      name: http
  selector:
    app: dashboard


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard-v1
  labels:
    app: dashboard
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboard
      version: v1
  template:
    spec:
      containers:
        - image: v1-new-app:0.0.1
          name: dashboard
          imagePullPolicy: Never
    metadata:
      labels:
        app: dashboard
        version: v1

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard-v2
  labels:
    app: dashboard
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboard
      version: v2
  template:
    spec:
      containers:
        - image: v1-new-app:0.0.1
          name: dashboard
          imagePullPolicy: Never
    metadata:
      labels:
        app: dashboard
        version: v2