apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: single-versioned-svc
spec:
  project: service-mesh
  source:
    repoURL: https://github.com/saitejdandge/servicemesh.git
    targetRevision: HEAD
    path: single-versioned-svc/app
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
