apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-v1
  labels:
    app: login
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login
      version: v1
  template:
    spec:
      containers:
        - image: user-image:v1
          name: login
          imagePullPolicy: Never
    metadata:
      labels:
        app: login
        version: v1