#kubectl apply -k dir/.
#kubectl apply -k single-versioned-deployment/argo-cd/.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: single-versioned-svc
resources:
  - resources/namespace.yml
  - resources/deployment:0.0.2.yml
  - resources/single-service.yml
  - resources/destination-rule.yml
  - resources/virtual-svc:0.0.1.yml
  - resources/application.yml